name: 'Drift CI'
description: 'Autonomous pattern-aware code analysis for pull requests'
author: 'dadbodgeoff'

branding:
  icon: 'git-pull-request'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  
  fail-on-violation:
    description: 'Fail the action if violations are found'
    required: false
    default: 'false'
  
  post-comment:
    description: 'Post analysis results as PR comment'
    required: false
    default: 'true'
  
  create-check:
    description: 'Create a check run with annotations'
    required: false
    default: 'true'
  
  pattern-check:
    description: 'Enable pattern violation checking'
    required: false
    default: 'true'
  
  impact-analysis:
    description: 'Enable impact analysis'
    required: false
    default: 'true'
  
  constraint-verification:
    description: 'Enable constraint verification'
    required: false
    default: 'true'
  
  security-boundaries:
    description: 'Enable security boundary checking'
    required: false
    default: 'true'
  
  memory-enabled:
    description: 'Enable Cortex memory for learning'
    required: false
    default: 'true'

outputs:
  status:
    description: 'Analysis status (pass, warn, fail)'
  
  summary:
    description: 'Analysis summary'
  
  violations-count:
    description: 'Number of violations found'
  
  drift-score:
    description: 'Drift score (0-100)'
  
  result-json:
    description: 'Full analysis result as JSON'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Drift CI
      shell: bash
      run: npm install -g driftdetect-ci@latest

    - name: Run Drift CI Analysis
      id: drift
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Extract PR number from event
        PR_NUMBER="${{ github.event.pull_request.number }}"
        
        if [ -z "$PR_NUMBER" ]; then
          echo "::error::This action must be run on a pull_request event"
          exit 1
        fi
        
        # Build command
        CMD="drift-ci analyze --pr $PR_NUMBER"
        CMD="$CMD --owner ${{ github.repository_owner }}"
        CMD="$CMD --repo ${{ github.event.repository.name }}"
        
        if [ "${{ inputs.post-comment }}" != "true" ]; then
          CMD="$CMD --no-comment"
        fi
        
        if [ "${{ inputs.create-check }}" != "true" ]; then
          CMD="$CMD --no-check"
        fi
        
        if [ "${{ inputs.fail-on-violation }}" == "true" ]; then
          CMD="$CMD --fail-on-violation"
        fi
        
        # Run analysis and capture output
        RESULT=$($CMD --json 2>&1) || EXIT_CODE=$?
        
        # Parse results
        STATUS=$(echo "$RESULT" | jq -r '.status // "error"')
        SUMMARY=$(echo "$RESULT" | jq -r '.summary // "Analysis failed"')
        VIOLATIONS=$(echo "$RESULT" | jq -r '(.patterns.violations | length) + (.constraints.violated | length)')
        DRIFT_SCORE=$(echo "$RESULT" | jq -r '.patterns.driftScore // 0')
        
        # Set outputs
        echo "status=$STATUS" >> $GITHUB_OUTPUT
        echo "summary=$SUMMARY" >> $GITHUB_OUTPUT
        echo "violations-count=$VIOLATIONS" >> $GITHUB_OUTPUT
        echo "drift-score=$DRIFT_SCORE" >> $GITHUB_OUTPUT
        
        # Store full result (escaped for multiline)
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "result-json<<$EOF" >> $GITHUB_OUTPUT
        echo "$RESULT" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
        
        # Exit with captured code if fail-on-violation
        if [ -n "$EXIT_CODE" ]; then
          exit $EXIT_CODE
        fi
