// Barrel re-exports for all NAPI contract types
export type { InitOptions, ProgressUpdate, ProgressCallback } from './lifecycle.js';
export type {
  ScanOptions,
  ScanSummary,
  ScanStatsJs,
} from './scanner.js';
export type {
  JsAnalysisResult,
  JsPatternMatch,
  JsCallGraphResult,
  JsBoundaryResult,
  JsModelResult,
  JsSensitiveField,
} from './analysis.js';
export type {
  PatternsResult,
  PatternEntry,
  ConfidenceResult,
  ConfidenceScore,
  OutlierResult,
  OutlierEntry,
  ConventionResult,
  ConventionEntry,
} from './patterns.js';
export type {
  JsReachabilityResult,
  JsTaintFlow,
  JsTaintResult,
  JsErrorGap,
  JsErrorHandlingResult,
  JsBlastRadius,
  JsDeadCode,
  JsImpactResult,
  JsTestQuality,
  JsTestTopologyResult,
} from './graph.js';
export type {
  JsCouplingMetrics,
  JsCycleInfo,
  JsCouplingResult,
  JsConstraintViolation,
  JsConstraintResult,
  JsEndpoint,
  JsContractMismatch,
  JsContractResult,
  JsSecret,
  JsMagicNumber,
  JsConstantsResult,
  JsWrapper,
  JsWrapperHealth,
  JsWrapperResult,
  JsGene,
  JsMutation,
  JsDnaHealthScore,
  JsDnaResult,
  JsSecurityFinding,
  JsComplianceReport,
  JsOwaspResult,
  JsCryptoFinding,
  JsCryptoHealthScore,
  JsCryptoResult,
  JsLogicalModule,
  JsDecompositionResult,
} from './structural.js';
export type {
  JsViolation,
  JsGateResult,
  JsCheckResult,
  JsHealthBreakdown,
  JsAuditResult,
  JsFeedbackInput,
  JsFeedbackResult,
  GcResult,
  GcTableResult,
} from './enforcement.js';
export type {
  SimulationResult,
  SimulationStrategy,
  DecisionResult,
  DecisionEntry,
  ContextResult,
  ContextSection,
  SpecResult,
  SpecSection,
} from './advanced.js';
export type {
  BridgeStatusResult,
  BridgeHealthResult,
  BridgeSubsystemCheck,
  BridgeGroundingResult,
  BridgeGroundingSnapshot,
  BridgeGroundingHistoryEntry,
  BridgeGroundingHistoryResult,
  BridgeEntityLink,
  BridgeEventMapping,
  BridgeEventMappingsResult,
  BridgeGroundabilityResult,
  BridgeIntentEntry,
  BridgeIntentsResult,
  BridgeLicenseResult,
  BridgeAdaptiveWeightsResult,
  BridgeSpecCorrectionResult,
  BridgeContractVerifiedResult,
  BridgeDecompositionAdjustedResult,
  BridgeExplainSpecResult,
  BridgeCounterfactualResult,
  BridgeInterventionResult,
  BridgeUnifiedNarrativeResult,
  BridgePruneCausalResult,
} from './bridge.js';
